version: '3.8'

services:
  db:
    image: mysql:8.0.30
    container_name: example-sql-class
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: chinook
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./database/chinook.sql:/docker-entrypoint-initdb.d/chinook.sql

  backend:
    build: ./backend
    restart: always
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chinook
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8888:8888"

  frontend:
    build: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  mysql_data:
